baseURL = "https://orienteering-allgaeu.de/"
languageCode = "de-de"
title = "Orienteering Allgäu"
theme = "cleanwhite"
mainSections = ["news"]                      # Sets the News section as the landing page
preserveTaxonomyNames = true # Required by the cleanwhite theme
hasCJKLanguage = false # Set to true if you use Chinese/Japanese/Korean

[outputs]
home = ["HTML", "RSS"] # Adjusted based on cleanwhite theme defaults

[params]
description = "Orientierungslauf im Allgäu" # Your existing description
header_image = "images/home-bg.jpg" # Placeholder: add your image to static/images/
image_404 = "images/404-bg.jpg"     # Placeholder: add your image to static/images/
sidebar_about_description = "Orientierungslauf im Allgäu und Umgebung" # Customize as needed
sidebar_avatar = "images/avatar.png" # Placeholder: add your avatar to static/images/
upstreamAttribution = true # Theme specific: shows theme attribution
omit_categories = false    # Theme specific: shows categories
algolia_search = false     # Disabled Algolia search for now

  [params.social]
  rss            = true
  # email          = "your-email@example.com"
  # github         = "your-github-profile"
  # linkedin       = "your-linkedin-profile"
  # Add other social links as needed

# Pagination settings from cleanwhite theme
[pagination]
  pagerSize = 10

[menu]
[[menu.main]]
identifier = "news"
name = "News"
url = "/news/"
weight = 10
[[menu.main]]
identifier = "events"
name = "Termine"
url = "/events/"
weight = 20
[[menu.main]]
identifier = "maps"
name = "Karten"
url = "/maps/"
weight = 30
[[menu.main]]
identifier = "wasistol"
name = "Was ist OL?"
url = "https://o-sport.de/ol/informationen/was-ist-ol/"
weight = 40

[[menu.footer]]
identifier = "impressum"
name = "Impressum"
url = "/impressum/"
weight = 10

# Markup settings from cleanwhite theme
[markup]
  [markup.tableOfContents]
    endLevel = 2
    startLevel = 1
  [markup.highlight]
    style = "dracula" # Code highlighting style
  [markup.goldmark.renderer]
    unsafe = true # Allows raw HTML in markdown, needed by some themes/content
