baseURL = 'https://orienteering-allgaeu.de/'
languageCode = 'de-de'
title = 'Orienteering Allgäu'
theme = "hugo-theme-cleanwhite"
preserveTaxonomyNames = true

[pagination]
pagerSize = 5

[params]
header_image = "img/default-banner.webp"
SEOTitle = "Orienteering Allgäu | Orientierungslauf im Allgäu"
description = "Orientierungslauf im Allgäu - Termine, Ergebnisse und Informationen rund um den Orientierungssport in der Region"
keyword = "Orientierungslauf, Allgäu, OL, Orienteering, Sport, Laufen"
# slogan = "Orientierung ist alles"

# Custom CSS files
custom_css = ["css/custom.css"]

# Section-specific banner images
[params.section_images]
# termine = "img/termine-banner.webp"
karten = "img/karten-banner.png"
# about = "img/about-banner.webp"

# Sidebar settings
# sidebar_about_description = "Orientierungslauf im Allgäu"
# sidebar_avatar = "img/avatar.jpg"

featured_tags = false
featured_condition_size = 1

# Social links
[params.social]
rss = true
email = "info@orienteering-allgaeu.de"

# Additional menu items
[[params.additional_menus]]
title = "TERMINE"
href = "/termine/"
[[params.additional_menus]]
title = "KARTEN"
href = "/karten/"
[[params.additional_menus]]
title = "WAS IST OL?"
href = "https://o-sport.de/ol/informationen/was-ist-ol/"
[[params.additional_menus]]
title = "MAPANT"
href = "https://mapant.orienteering-allgaeu.de"
[[params.additional_menus]]
title = "ÜBER UNS"
href = "/about/"
