# Workflow for building Hugo site and deploying to GitHub Pages with PR previews
name: Build and Deploy Hugo Site

on:
  push:
    branches:
      - main
  pull_request:
    # also run on 'closed' to clean up the github pages dir
    types:
      - opened
      - reopened
      - synchronize
      - closed

concurrency: preview-${{ github.ref }}

jobs:
  docs:
    name: "Build Page"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          filter: blob:none

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true

      - name: Setup Node.js (for potential post-processing)
        uses: actions/setup-node@v4
        with:
          node-version: '18'
  
      - name: Build with Hugo (production)
        if: github.event_name != 'pull_request'
        run: hugo --minify

      - name: Build with Hugo (PR preview)
        if: github.event_name == 'pull_request'
        run: hugo --minify --baseURL "https://orienteering-allgaeu.de/pr-preview/pr-${{ github.event.number }}/"

      - name: Deploy preview
        if: github.event_name == 'pull_request'
        uses: rossjrw/pr-preview-action@v1
        with:
          source-dir: ./public 
          pages-base-url: orienteering-allgaeu.de

      - name: Deploy site 
        if: github.event_name != 'pull_request'
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: ./public
          branch: gh-pages
          clean-exclude: pr-preview/
          force: false
